MODULE:=oonf_$(shell basename $(CURDIR))
INCLUDES = -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/sys/net/include -I$(OONFBASE)/src-api \
           -I$(RIOTBASE)/boards/$(BOARD)/include -I$(RIOTBASE)/cpu/$(BOARD)/include

include $(RIOTBASE)/Makefile.base
