MODULE:=oonf_$(shell basename $(CURDIR))
INCLUDES = -I$(RIOTBASE) -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/cc110x_ng/include \
	-I$(RIOTBASE)/sys/net/include -I$(OONFBASE)/src-api -I$(RIOTLIBS)

include $(RIOTBASE)/Makefile.base
